**Import Library**

In [2]:
import pandas as pd

In [62]:
set = pd.read_csv('../Data/top20_set_prices.csv')

**Data cleaning for SET and S&P500**

**SET**

In [6]:
set.shape

(2664, 145)

In [7]:
set

,Price,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Adj Close.8,...,Volume.14,Volume.15,Volume.16,Volume.17,Volume.18,Volume.19,Volume.20,Volume.21,Volume.22,Volume.23
0,Ticker,ADVANC.BK,AOT.BK,BBL.BK,BDMS.BK,BH.BK,CPALL.BK,CPF.BK,CPN.BK,CRC.BK,...,KBANK.BK,KTB.BK,MINT.BK,OR.BK,PTT.BK,PTTEP.BK,SCB.BK,SCC.BK,TRUE.BK,TTB.BK
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-02,115.70769500732422,13.004045486450195,112.16766357421875,8.86504077911377,68.68024444580078,33.13692855834961,22.704105377197266,31.58096694946289,NaN,...,17348400,84143600,11274079,NaN,34484000,5548200,NaN,1199400,194202011,258678302
3,2014-01-03,121.27652740478516,12.87090015411377,113.85691833496094,8.824374198913574,69.91403198242188,33.13692855834961,22.704105377197266,31.15988540649414,NaN,...,14007700,57976000,9399961,NaN,46203000,5289100,NaN,2618000,296473487,287311397
4,2014-01-06,124.37032318115234,12.648985862731934,117.23546600341797,9.6783447265625,69.0915298461914,33.34403991699219,21.773605346679688,31.58096694946289,NaN,...,17816000,68818900,19638150,NaN,62204000,7342300,NaN,1589200,192726833,189481489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2659,2024-12-03,296.0,61.209999084472656,150.5,26.0,212.0,63.75,24.200000762939453,60.5,34.5,...,17862300,20105200,16294100,5921900.0,17691100,4910000,11866600.0,3259900,37514700,94356000
2660,2024-12-04,289.0,61.5,151.5,25.75,211.0,64.0,24.100000381469727,60.5,33.75,...,16038900,37336500,25590400,4270200.0,30338600,4505000,12380400.0,3534900,52679100,136620600
2661,2024-12-06,295.0,61.0,152.0,25.5,210.0,63.0,24.100000381469727,60.25,34.0,...,7544400,22619700,9642900,6112100.0,24310500,2427800,5165800.0,2436600,52769200,286700300
2662,2024-12-09,295.0,60.5,153.0,25.25,202.0,62.75,23.899999618530273,59.75,34.0,...,17093200,86469800,10810400,6942300.0,12600200,5833300,6849700.0,2925600,22723500,152718400
2663,2024-12-11,289.0,61.5,151.0,25.25,199.5,63.0,23.899999618530273,59.5,34.25,...,9896700,39048000,14136000,5352500.0,33668400,6732800,5862600.0,7035100,102588600,114100700

In [8]:
# drop all the columns except for Adj Close
set = set[[col for col in set.columns if col.startswith(('Price', 'Adj'))]]

In [9]:
set.columns

Index(['Price', 'Adj Close', 'Adj Close.1', 'Adj Close.2', 'Adj Close.3',
       'Adj Close.4', 'Adj Close.5', 'Adj Close.6', 'Adj Close.7',
       'Adj Close.8', 'Adj Close.9', 'Adj Close.10', 'Adj Close.11',
       'Adj Close.12', 'Adj Close.13', 'Adj Close.14', 'Adj Close.15',
       'Adj Close.16', 'Adj Close.17', 'Adj Close.18', 'Adj Close.19',
       'Adj Close.20', 'Adj Close.21', 'Adj Close.22', 'Adj Close.23'],
      dtype='object')

In [10]:
# Reset the index by the name of the stocks 
set.columns = set.iloc[0]
# Drop all the stocks name rows and NaN rows 
set = set[2:]

In [11]:
set.isnull().sum()[set.isnull().sum() != 0]

0
CRC.BK     1498
GULF.BK     958
OR.BK      1735
SCB.BK     2023
dtype: int64

In [12]:
# Seperate the (CRC, GULF, OR, and SCB) into different 
the_rest = set[['CRC.BK', 'GULF.BK', 'OR.BK','SCB.BK']]
the_rest

0    CRC.BK GULF.BK               OR.BK SCB.BK
2       NaN     NaN                 NaN    NaN
3       NaN     NaN                 NaN    NaN
4       NaN     NaN                 NaN    NaN
5       NaN     NaN                 NaN    NaN
6       NaN     NaN                 NaN    NaN
...     ...     ...                 ...    ...
2659   34.5    65.5  14.300000190734863  116.0
2660  33.75   63.25  14.100000381469727  118.0
2661   34.0    65.0  14.100000381469727  118.0
2662   34.0   64.25  13.899999618530273  118.5
2663  34.25   63.25  14.100000381469727  118.0

[2662 rows x 4 columns]

In [13]:
main = set.drop(columns = ['CRC.BK', 'GULF.BK', 'OR.BK','SCB.BK'])
main = main.rename(columns ={'Ticker':'Date'})

In [14]:
# set date to date 
main['Date'] = pd.to_datetime(main['Date'])

# set date into index 
main = main.set_index('Date')

In [15]:
# Converting all the obj into float
for col in main.columns[1:21] :
        main[col] = main[col].astype(float)

In [16]:
# Export the file 
main.to_csv("../Data/SET_main.csv")
the_rest.to_csv("../Data/SET_residual.csv")

In [106]:
main

,ADVANC.BK,AOT.BK,BBL.BK,BDMS.BK,BH.BK,CPALL.BK,CPF.BK,CPN.BK,DELTA.BK,HMPRO.BK,INTUCH.BK,IVL.BK,KBANK.BK,KTB.BK,MINT.BK,PTT.BK,PTTEP.BK,SCC.BK,TRUE.BK,TTB.BK
Date,,,,,,,,,,,,,,,,,,,,
2014-01-02,115.70769500732422,13.004045,112.167664,8.865041,68.680244,33.136929,22.704105,31.580967,4.015339,4.772995,36.063667,14.913610,107.741776,9.801532,15.467829,16.889353,93.353264,263.643036,5.398062,1.198794
2014-01-03,121.27652740478516,12.870900,113.856918,8.824374,69.914032,33.136929,22.704105,31.159885,3.846470,4.633434,36.908916,14.837523,111.814484,9.864767,15.223605,16.519508,92.148727,262.951050,5.318678,1.186436
2014-01-06,124.37032318115234,12.648986,117.235466,9.678345,69.091530,33.344040,21.773605,31.580967,3.696364,4.605521,37.190655,14.913610,116.257446,9.991237,16.363337,16.272951,89.137291,266.411011,5.477446,1.217332
2014-01-07,129.9391326904297,13.447869,120.276161,9.556350,68.474625,33.965351,22.704105,32.844200,3.771417,4.717172,38.176777,15.446239,119.959915,10.244180,17.096024,17.320827,92.449844,269.178833,5.636212,1.229691
2014-01-08,127.46409606933594,12.870900,119.938301,9.312360,67.446480,33.551147,22.145803,32.633663,3.790180,4.633434,38.035904,15.978869,119.959915,9.991237,16.526155,17.567392,94.256668,271.254791,5.398062,1.248229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-03,296.0,61.209999,150.500000,26.000000,212.000000,63.750000,24.200001,60.500000,151.000000,9.900000,102.500000,24.600000,153.500000,20.299999,27.750000,32.250000,128.500000,184.000000,11.900000,1.790000
2024-12-04,289.0,61.500000,151.500000,25.750000,211.000000,64.000000,24.100000,60.500000,151.000000,9.700000,100.000000,24.500000,155.000000,20.600000,28.000000,32.250000,128.000000,183.000000,12.100000,1.780000
2024-12-06,295.0,61.000000,152.000000,25.500000,210.000000,63.000000,24.100000,60.250000,150.500000,9.700000,102.500000,25.250000,156.000000,20.700001,27.500000,32.250000,128.000000,183.500000,11.800000,1.830000
2024-12-09,295.0,60.500000,153.000000,25.250000,202.000000,62.750000,23.900000,59.750000,152.500000,9.650000,101.500000,25.500000,156.500000,21.500000,27.250000,32.000000,126.500000,179.000000,11.800000,1.830000
2024-12-11,289.0,61.500000,151.000000,25.250000,199.500000,63.000000,23.900000,59.500000,151.000000,9.750000,101.500000,26.000000,154.500000,21.000000,27.500000,32.250000,125.000000,173.000000,11.900000,1.830000

**S&P500**

In [118]:
sp500 = pd.read_csv('../Data/top20_sp500_prices.csv')

In [120]:
list(sp500.columns)

['Price',
 'Adj Close',
 'Adj Close.1',
 'Adj Close.2',
 'Adj Close.3',
 'Adj Close.4',
 'Adj Close.5',
 'Adj Close.6',
 'Adj Close.7',
 'Adj Close.8',
 'Adj Close.9',
 'Adj Close.10',
 'Adj Close.11',
 'Adj Close.12',
 'Adj Close.13',
 'Adj Close.14',
 'Adj Close.15',
 'Adj Close.16',
 'Adj Close.17',
 'Adj Close.18',
 'Adj Close.19',
 'Close',
 'Close.1',
 'Close.2',
 'Close.3',
 'Close.4',
 'Close.5',
 'Close.6',
 'Close.7',
 'Close.8',
 'Close.9',
 'Close.10',
 'Close.11',
 'Close.12',
 'Close.13',
 'Close.14',
 'Close.15',
 'Close.16',
 'Close.17',
 'Close.18',
 'Close.19',
 'High',
 'High.1',
 'High.2',
 'High.3',
 'High.4',
 'High.5',
 'High.6',
 'High.7',
 'High.8',
 'High.9',
 'High.10',
 'High.11',
 'High.12',
 'High.13',
 'High.14',
 'High.15',
 'High.16',
 'High.17',
 'High.18',
 'High.19',
 'Low',
 'Low.1',
 'Low.2',
 'Low.3',
 'Low.4',
 'Low.5',
 'Low.6',
 'Low.7',
 'Low.8',
 'Low.9',
 'Low.10',
 'Low.11',
 'Low.12',
 'Low.13',
 'Low.14',
 'Low.15',
 'Low.16',
 'Low.17',
 'Low.18',
 'Low.19',
 'Open',
 'Open.1',
 'Open.2',
 'Open.3',
 'Open.4',
 'Open.5',
 'Open.6',
 'Open.7',
 'Open.8',
 'Open.9',
 'Open.10',
 'Open.11',
 'Open.12',
 'Open.13',
 'Open.14',
 'Open.15',
 'Open.16',
 'Open.17',
 'Open.18',
 'Open.19',
 'Volume',
 'Volume.1',
 'Volume.2',
 'Volume.3',
 'Volume.4',
 'Volume.5',
 'Volume.6',
 'Volume.7',
 'Volume.8',
 'Volume.9',
 'Volume.10',
 'Volume.11',
 'Volume.12',
 'Volume.13',
 'Volume.14',
 'Volume.15',
 'Volume.16',
 'Volume.17',
 'Volume.18',
 'Volume.19']

In [122]:
# Drop all the columns except for Adj Close
sp500 = sp500.iloc[:, :21]
sp500

,Price,Adj Close,Adj Close.1,Adj Close.2,Adj Close.3,Adj Close.4,Adj Close.5,Adj Close.6,Adj Close.7,Adj Close.8,...,Adj Close.10,Adj Close.11,Adj Close.12,Adj Close.13,Adj Close.14,Adj Close.15,Adj Close.16,Adj Close.17,Adj Close.18,Adj Close.19
0,Ticker,AAPL,AMZN,AVGO,COST,GOOG,GOOGL,HD,JPM,LLY,...,META,MSFT,NVDA,ORCL,PG,TSLA,UNH,V,WMT,XOM
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-02,17.234296798706055,19.898500442504883,3.9612834453582764,94.36917877197266,27.62482452392578,27.75524139404297,63.56880187988281,43.28535079956055,40.58515167236328,...,54.54576873779297,31.058565139770508,0.373966246843338,32.0086555480957,58.940643310546875,10.006667137145996,63.01327133178711,51.132057189941406,21.05429458618164,62.73944091796875
3,2014-01-03,16.855730056762695,19.82200050354004,3.9763312339782715,93.9526596069336,27.423307418823242,27.552770614624023,63.468048095703125,43.6199836730957,40.88115310668945,...,54.39622116088867,30.8496036529541,0.3694862723350525,31.92379379272461,58.87478256225586,9.970666885375977,63.46112823486328,51.166770935058594,20.984922409057617,62.588504791259766
4,2014-01-06,16.94764518737793,19.681499481201172,3.9492456912994385,93.23973083496094,27.72905921936035,27.859968185424805,62.85575485229492,43.8728141784668,41.225162506103516,...,57.02829360961914,30.197683334350586,0.37443774938583374,31.796506881713867,59.01380157470703,9.800000190734863,62.73441696166992,50.85905838012695,20.867523193359375,62.68283462524414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2752,2024-12-05,243.0399932861328,220.5500030517578,170.47000122070312,982.260009765625,174.1124725341797,172.44236755371094,426.5400085449219,245.47999572753906,825.6199951171875,...,608.9299926757812,442.6199951171875,145.05999755859375,186.24000549316406,176.02999877929688,369.489990234375,576.7578125,309.0799865722656,95.30000305175781,114.77999877929688
2753,2024-12-06,242.83999633789062,227.02999877929688,179.52999877929688,992.6099853515625,176.29000854492188,174.510009765625,431.3699951171875,247.36000061035156,826.7100219726562,...,623.77001953125,443.57000732421875,142.44000244140625,191.69000244140625,173.82000732421875,389.2200012207031,547.5199584960938,311.010009765625,95.69999694824219,113.56999969482422
2754,2024-12-09,246.75,226.08999633789062,178.94000244140625,987.8599853515625,177.10000610351562,175.3699951171875,429.17999267578125,243.80999755859375,803.5800170898438,...,613.5700073242188,446.0199890136719,138.80999755859375,190.4499969482422,170.7899932861328,389.7900085449219,560.6199951171875,308.29998779296875,93.83000183105469,112.9000015258789
2755,2024-12-10,247.77000427246094,225.0399932861328,171.80999755859375,993.4000244140625,186.52999877929688,185.1699981689453,422.5899963378906,242.86000061035156,799.5800170898438,...,619.3200073242188,443.3299865722656,135.07000732421875,177.74000549316406,172.27999877929688,400.989990234375,565.1900024414062,312.3800048828125,94.55000305175781,112.66999816894531
2756,2024-12-11,246.49000549316406,230.25999450683594,183.1999969482422,994.6900024414062,196.7100067138672,195.39999389648438,421.3800048828125,243.52999877929688,796.030029296875,...,632.6799926757812,448.989990234375,139.30999755859375,178.5800018310547,170.6300048828125,424.7699890136719,533.530029296875,313.7900085449219,94.95999908447266,111.91999816894531

In [124]:
# Reset the index by the name of the stocks 
sp500.columns = sp500.iloc[0]
# Drop all the stocks name rows and NaN rows 
sp500 = sp500[2:]

sp500

,Ticker,AAPL,AMZN,AVGO,COST,GOOG,GOOGL,HD,JPM,LLY,...,META,MSFT,NVDA,ORCL,PG,TSLA,UNH,V,WMT,XOM
2,2014-01-02,17.234296798706055,19.898500442504883,3.9612834453582764,94.36917877197266,27.62482452392578,27.75524139404297,63.56880187988281,43.28535079956055,40.58515167236328,...,54.54576873779297,31.058565139770508,0.373966246843338,32.0086555480957,58.940643310546875,10.006667137145996,63.01327133178711,51.132057189941406,21.05429458618164,62.73944091796875
3,2014-01-03,16.855730056762695,19.82200050354004,3.9763312339782715,93.9526596069336,27.423307418823242,27.552770614624023,63.468048095703125,43.6199836730957,40.88115310668945,...,54.39622116088867,30.8496036529541,0.3694862723350525,31.92379379272461,58.87478256225586,9.970666885375977,63.46112823486328,51.166770935058594,20.984922409057617,62.588504791259766
4,2014-01-06,16.94764518737793,19.681499481201172,3.9492456912994385,93.23973083496094,27.72905921936035,27.859968185424805,62.85575485229492,43.8728141784668,41.225162506103516,...,57.02829360961914,30.197683334350586,0.37443774938583374,31.796506881713867,59.01380157470703,9.800000190734863,62.73441696166992,50.85905838012695,20.867523193359375,62.68283462524414
5,2014-01-07,16.826440811157227,19.901500701904297,3.9868650436401367,92.80715942382812,28.263626098632812,28.397058486938477,63.16579055786133,43.367156982421875,40.953147888183594,...,57.74612808227539,30.431716918945312,0.38056838512420654,32.11896514892578,59.584632873535156,9.957332611083984,64.65264129638672,51.24774169921875,20.931564331054688,63.56968307495117
6,2014-01-08,16.93300437927246,20.09600067138672,4.046302795410156,91.35733032226562,28.322444915771484,28.456151962280273,63.4990348815918,43.7761344909668,40.88914108276367,...,58.05520248413086,29.88844108581543,0.3857557773590088,32.00865173339844,58.721099853515625,10.085332870483398,63.90058517456055,51.41199493408203,20.76613998413086,63.36212158203125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2752,2024-12-05,243.0399932861328,220.5500030517578,170.47000122070312,982.260009765625,174.1124725341797,172.44236755371094,426.5400085449219,245.47999572753906,825.6199951171875,...,608.9299926757812,442.6199951171875,145.05999755859375,186.24000549316406,176.02999877929688,369.489990234375,576.7578125,309.0799865722656,95.30000305175781,114.77999877929688
2753,2024-12-06,242.83999633789062,227.02999877929688,179.52999877929688,992.6099853515625,176.29000854492188,174.510009765625,431.3699951171875,247.36000061035156,826.7100219726562,...,623.77001953125,443.57000732421875,142.44000244140625,191.69000244140625,173.82000732421875,389.2200012207031,547.5199584960938,311.010009765625,95.69999694824219,113.56999969482422
2754,2024-12-09,246.75,226.08999633789062,178.94000244140625,987.8599853515625,177.10000610351562,175.3699951171875,429.17999267578125,243.80999755859375,803.5800170898438,...,613.5700073242188,446.0199890136719,138.80999755859375,190.4499969482422,170.7899932861328,389.7900085449219,560.6199951171875,308.29998779296875,93.83000183105469,112.9000015258789
2755,2024-12-10,247.77000427246094,225.0399932861328,171.80999755859375,993.4000244140625,186.52999877929688,185.1699981689453,422.5899963378906,242.86000061035156,799.5800170898438,...,619.3200073242188,443.3299865722656,135.07000732421875,177.74000549316406,172.27999877929688,400.989990234375,565.1900024414062,312.3800048828125,94.55000305175781,112.66999816894531
2756,2024-12-11,246.49000549316406,230.25999450683594,183.1999969482422,994.6900024414062,196.7100067138672,195.39999389648438,421.3800048828125,243.52999877929688,796.030029296875,...,632.6799926757812,448.989990234375,139.30999755859375,178.5800018310547,170.6300048828125,424.7699890136719,533.530029296875,313.7900085449219,94.95999908447266,111.91999816894531

In [126]:
# change name from price to Date
sp500 = sp500.rename(columns ={'Ticker':'Date'})
# set date to date 
sp500['Date'] = pd.to_datetime(sp500['Date'])

# set date into index 
# sp500 = sp500.set_index('Date')

In [128]:
# Converting all the obj into float
for col in sp500.columns[1:21] :
        sp500[col] = sp500[col].astype(float)

In [136]:
# Export the file 
sp500.to_csv("../Data/sp500_main.csv", index=False)

In [132]:
# sp500 = pd.read_csv('../Data/sp500_main.csv')

In [134]:
sp500

,Date,AAPL,AMZN,AVGO,COST,GOOG,GOOGL,HD,JPM,LLY,...,META,MSFT,NVDA,ORCL,PG,TSLA,UNH,V,WMT,XOM
2,2014-01-02,17.234297,19.898500,3.961283,94.369179,27.624825,27.755241,63.568802,43.285351,40.585152,...,54.545769,31.058565,0.373966,32.008656,58.940643,10.006667,63.013271,51.132057,21.054295,62.739441
3,2014-01-03,16.855730,19.822001,3.976331,93.952660,27.423307,27.552771,63.468048,43.619984,40.881153,...,54.396221,30.849604,0.369486,31.923794,58.874783,9.970667,63.461128,51.166771,20.984922,62.588505
4,2014-01-06,16.947645,19.681499,3.949246,93.239731,27.729059,27.859968,62.855755,43.872814,41.225163,...,57.028294,30.197683,0.374438,31.796507,59.013802,9.800000,62.734417,50.859058,20.867523,62.682835
5,2014-01-07,16.826441,19.901501,3.986865,92.807159,28.263626,28.397058,63.165791,43.367157,40.953148,...,57.746128,30.431717,0.380568,32.118965,59.584633,9.957333,64.652641,51.247742,20.931564,63.569683
6,2014-01-08,16.933004,20.096001,4.046303,91.357330,28.322445,28.456152,63.499035,43.776134,40.889141,...,58.055202,29.888441,0.385756,32.008652,58.721100,10.085333,63.900585,51.411995,20.766140,63.362122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2752,2024-12-05,243.039993,220.550003,170.470001,982.260010,174.112473,172.442368,426.540009,245.479996,825.619995,...,608.929993,442.619995,145.059998,186.240005,176.029999,369.489990,576.757812,309.079987,95.300003,114.779999
2753,2024-12-06,242.839996,227.029999,179.529999,992.609985,176.290009,174.510010,431.369995,247.360001,826.710022,...,623.770020,443.570007,142.440002,191.690002,173.820007,389.220001,547.519958,311.010010,95.699997,113.570000
2754,2024-12-09,246.750000,226.089996,178.940002,987.859985,177.100006,175.369995,429.179993,243.809998,803.580017,...,613.570007,446.019989,138.809998,190.449997,170.789993,389.790009,560.619995,308.299988,93.830002,112.900002
2755,2024-12-10,247.770004,225.039993,171.809998,993.400024,186.529999,185.169998,422.589996,242.860001,799.580017,...,619.320007,443.329987,135.070007,177.740005,172.279999,400.989990,565.190002,312.380005,94.550003,112.669998
2756,2024-12-11,246.490005,230.259995,183.199997,994.690002,196.710007,195.399994,421.380005,243.529999,796.030029,...,632.679993,448.989990,139.309998,178.580002,170.630005,424.769989,533.530029,313.790009,94.959999,111.919998